[package]
name = "commons"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rsa = "0.9.6"
rand = "0.8.4"
pem = "3.0.4"
base64 = "0.20.0"
